CREATE TABLE IF NOT EXISTS ms_menu (
    id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, title VARCHAR(100) NOT NULL, path VARCHAR(100), icon_name VARCHAR(100), is_submenu BOOLEAN DEFAULT FALSE, parent_name VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP DEFAULT NULL
);