CREATE TABLE IF NOT EXISTS tb_log_login (
    id SERIAL PRIMARY KEY, agent VARCHAR(100) NOT NULL, email VARCHAR(150) NOT NULL, action VARCHAR(100) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP DEFAULT NULL
);