CREATE TABLE IF NOT EXISTS ms_users (
    id SERIAL PRIMARY KEY, user_unique_id VARCHAR(255) UNIQUE NOT NULL, open_id VARCHAR(100) NULL, username VARCHAR(255) NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true, role_id INT DEFAULT 1, profile_id INT DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL
);

-- ALTER TABLE ms_users
-- ADD FOREIGN KEY (role_id) REFERENCES ms_roles (id)

-- ALTER TABLE ms_users
-- ADD FOREIGN KEY (profile_id) REFERENCES user_profile (user_id)