-- Active: 1670510927842@@127.0.0.1@5432@db_document_builder
CREATE TABLE IF NOT EXISTS ms_roles (
    id SERIAL PRIMARY KEY, role_name VARCHAR(60), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL
)