CREATE TABLE IF NOT EXISTS user_profile (
    id SERIAL PRIMARY KEY, user_id INT NOT NULL, first_name VARCHAR(100) NULL, last_name VARCHAR(100) NULL, profile_image VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE (user_id)
);